# Generated by Django 5.2.6 on 2025-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_total_trips',
            field=models.IntegerField(default=0),
        ),
    ]
