# Generated by Django 5.2.6 on 2025-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_truck_total_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_total_trips',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
